### ISSUE TITLE
Implement switchable themes

### ISSUE THREAD

**Issue by SunderB** [SunderB/sonic-pi-phoenix-website#2]
## Implementation
For my test website, I used a system which changed which css file was active depending on the chosen theme. It also saves the selected theme in the browser’s local storage. Although the implementation on the website is broken, I’ve had it working before locally.

We could use the same approach, or try a different one if there’s a nicer way of doing it.

### Themes
The themes would be based off of the themes from the Qt GUI:
* Light (default)
* Dark
* High Contrast

All themes should have good contrast to make them accessible - this especially applies for the high contrast theme. See #6.

**Comment by ethancrawford** [comment]
> Although the implementation on the website is broken,

I suspect this is because you're using `window.onload = ...` multiple times. That only works to assign a single event handler AFAIK. In this case, the theme switcher event handler is being overwritten.
The method that allows multiple handlers per event is:
[addEventListener](https://developer.mozilla.org/en-US/docs/Web/API/EventTarget/addEventListener) 🙂

**Comment by SunderB** [comment]
Implemented in 35b12e8ae278b3142fd8ad5251338f258f184847
